#use_frameworks!

platform :ios, '8.0'

target 'SJFrameLayout_Example' do
  pod 'SJRouter'
  pod 'SJUIKit/Queues'
  pod 'SJUIKit/ObserverHelper'
  pod 'SJFrameLayout', :path => '../'
  #pod 'Masonry'
  #pod 'MyLayout'
#pod 'MMPlaceHolder', :inhibit_warnings => true
#pod 'SDAutoLayout'
#pod 'MTHawkeye'

  target 'SJFrameLayout_Tests' do
    inherit! :search_paths

    
  end
end
