#use_frameworks!

platform :ios, '8.0'

target 'SJFrameLayout_Example' do
  pod 'SJFrameLayout', :path => '../'
  pod 'SJUIKit/Queue'
pod 'Masonry'
#pod 'MMPlaceHolder', :inhibit_warnings => true
#pod 'SDAutoLayout'
#pod 'MTHawkeye'

  target 'SJFrameLayout_Tests' do
    inherit! :search_paths

    
  end
end
